import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  ImageRun,
} from "docx";
import { put } from "@vercel/blob";

/**
 * Parse markdown and convert to docx paragraphs
 */
function parseMarkdownToParagraphs(markdown: string): Paragraph[] {
  const lines = markdown.split("\n");
  const paragraphs: Paragraph[] = [];

  for (const line of lines) {
    // Handle headings
    if (line.startsWith("# ")) {
      paragraphs.push(
        new Paragraph({
          text: line.replace(/^#\s+/, ""),
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 200, after: 100 },
        })
      );
    } else if (line.startsWith("## ")) {
      paragraphs.push(
        new Paragraph({
          text: line.replace(/^##\s+/, ""),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 150, after: 80 },
        })
      );
    } else if (line.startsWith("### ")) {
      paragraphs.push(
        new Paragraph({
          text: line.replace(/^###\s+/, ""),
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 100, after: 60 },
        })
      );
    }
    // Handle bold text
    else if (line.includes("**")) {
      const parts = line.split(/\*\*/g);
      const children = parts.map((part, index) => {
        if (index % 2 === 1) {
          return new TextRun({
            text: part,
            bold: true,
          });
        }
        return new TextRun({
          text: part,
        });
      });

      paragraphs.push(
        new Paragraph({
          children,
          spacing: { after: 60 },
        })
      );
    }
    // Handle italic text
    else if (line.includes("*")) {
      const parts = line.split(/\*(?!\*)/g);
      const children = parts.map((part, index) => {
        if (index % 2 === 1) {
          return new TextRun({
            text: part,
            italics: true,
          });
        }
        return new TextRun({
          text: part,
        });
      });

      paragraphs.push(
        new Paragraph({
          children,
          spacing: { after: 60 },
        })
      );
    }
    // Handle bullet points
    else if (line.trim().startsWith("- ") || line.trim().startsWith("* ")) {
      paragraphs.push(
        new Paragraph({
          text: line.replace(/^[-*]\s+/, ""),
          bullet: {
            level: 0,
          },
          spacing: { after: 40 },
        })
      );
    }
    // Handle numbered lists
    else if (/^\d+\.\s/.test(line.trim())) {
      paragraphs.push(
        new Paragraph({
          text: line.replace(/^\d+\.\s/, ""),
          numbering: {
            reference: "default-numbering",
            level: 0,
          },
          spacing: { after: 40 },
        })
      );
    }
    // Handle code blocks
    else if (line.startsWith("```")) {
      // Skip code block markers
      continue;
    }
    // Handle inline code
    else if (line.includes("`")) {
      const parts = line.split(/`/g);
      const children = parts.map((part, index) => {
        if (index % 2 === 1) {
          return new TextRun({
            text: part,
            font: "Courier New",
            color: "666666",
          });
        }
        return new TextRun({
          text: part,
        });
      });

      paragraphs.push(
        new Paragraph({
          children,
          spacing: { after: 60 },
        })
      );
    }
    // Handle empty lines
    else if (line.trim() === "") {
      paragraphs.push(
        new Paragraph({
          text: "",
          spacing: { after: 100 },
        })
      );
    }
    // Regular paragraph
    else if (line.trim()) {
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: line,
              size: 24, // 12pt
            }),
          ],
          spacing: { after: 60 },
        })
      );
    }
  }

  return paragraphs;
}

/**
 * Generate Word document from markdown content
 */
export async function generateWordDocument(
  markdown: string,
  title: string
): Promise<Buffer> {
  const paragraphs = parseMarkdownToParagraphs(markdown);

  // Create document
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          // Title page
          new Paragraph({
            text: title,
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { before: 400, after: 400 },
          }),
          new Paragraph({
            text: "Generated by Super Student Kit",
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),
          new Paragraph({
            text: new Date().toLocaleDateString(),
            alignment: AlignmentType.CENTER,
            spacing: { after: 800 },
          }),
          // Content
          ...paragraphs,
        ],
      },
    ],
  });

  // Generate buffer
  const buffer = await Packer.toBuffer(doc);
  return buffer;
}

/**
 * Upload Word document to blob storage
 */
export async function uploadWordDocument(
  buffer: Buffer,
  assignmentId: string,
  title: string
): Promise<string> {
  const filename = `${title.replace(/[^a-z0-9]/gi, "_")}_${assignmentId}.docx`;

  const blob = await put(filename, buffer, {
    access: "public",
    addRandomSuffix: true,
    contentType:
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  });

  return blob.url;
}

/**
 * Generate and upload Word document for an assignment
 */
export async function createAssignmentWordDocument(
  markdown: string,
  assignmentId: string,
  title: string
): Promise<string> {
  const buffer = await generateWordDocument(markdown, title);
  const url = await uploadWordDocument(buffer, assignmentId, title);
  return url;
}
